---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: quay.io/desource/alpine-build

inputs:
  - name: kibana-src
    path: src

outputs:
  - name: kibana-build
  
run:
  path: ./src/build.sh
